// <auto-generated />
using GruppKniv.Services.ProductsAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GruppKniv.Services.ProductsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221206182954_addedFirstMigrationProductsAPI")]
    partial class addedFirstMigrationProductsAPI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GruppKniv.Services.ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingridients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ImageUrl = "https://gruppkniv.blob.core.windows.net/gruppkniv/pizza-vesuvio.jpeg",
                            Ingridients = "Ost, Skinka, Tomatsås Gluten",
                            Name = "Vesuvio",
                            Price = 85.0
                        },
                        new
                        {
                            ProductId = 2,
                            ImageUrl = "https://gruppkniv.blob.core.windows.net/gruppkniv/stellas-kebabpizza.png.jpg",
                            Ingridients = "Ost, Kebab, Tomat, Färsk Sallad, Kebabsås, Gluten",
                            Name = "Kebab Pizza",
                            Price = 100.0
                        },
                        new
                        {
                            ProductId = 3,
                            ImageUrl = "https://gruppkniv.blob.core.windows.net/gruppkniv/calzone.jpg",
                            Ingridients = "Ost, Skinka, Tomatsås, Gluten",
                            Name = "Calzone",
                            Price = 95.0
                        },
                        new
                        {
                            ProductId = 4,
                            ImageUrl = "https://gruppkniv.blob.core.windows.net/gruppkniv/hawaiian-pizza-recipe-605894-2.jpg",
                            Ingridients = "Ost, Skinka, Ananas,Tomatsås, Gluten",
                            Name = "Hawaii",
                            Price = 85.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
